### ISSUE TITLE
pyopia process fails if correctbackground step is missing

### ISSUE THREAD

**Issue by emlynjdavies** [SINTEF/pyopia#282]
**Describe the bug**
pyopia process fails if correctbackground step is missing
line 135 in pyopia.cli

**To Reproduce**
run pyopia process with no correctbackground step in the config

**Expected behavior**
process without background correction

**Comment by emlynjdavies** [comment]
Maybe this is a workaround:

```toml
    [steps.correctbackground]
    pipeline_class = 'pyopia.background.CorrectBackgroundAccurate'
    average_window = 0 # number of images used to create background
    bgshift_function = 'pass' # optional 'fast' or 'accurate' method for moving backgrounds. For static background use 'pass' or comment this line.
```
